# Generated by Django 4.1.2 on 2022-10-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="age",
            field=models.IntegerField(),
        ),
    ]
