# Generated by Django 4.1.2 on 2022-10-31 00:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("vida cotidiana", "VIDA COTIDIANA"),
                            ("tecnologia", "TECNOLOGIA"),
                            ("cocina", "COCINA"),
                            ("debate", "DEBATE"),
                        ],
                        default="vida cotidiana",
                        max_length=25,
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
